Update extensions to build 2017-06-13
mit-cml/iot-website-source pull request #129
Opened 2017-06-14 01:40 UTC by ewpatton

This PR includes updated versions of the extensions to address a number of bugs reported on the forum as well as to add a few new blocks to aid in getting information about the connected device and its services in a more App Inventor friendly way.

2017-06-14 11:02 UTC, ewpatton commented
Do not merge yet. I am looking into two more possible bugs and will update this commit.

2017-06-14 19:26 UTC, ewpatton commented
This is now the latest version of the extensions. It includes some additional bug fixes and adds the AutoReconnect and ConnectionTimeout properties to the BluetoothLE extension.

2017-06-14 21:33 UTC, ewpatton commented
Do not merge (again). Some extensions need to have URLs fixed based on issue #134

2017-06-14 21:45 UTC, ewpatton commented
Fixed links to PDFs in accel and gyro components of Arduino 101. Removed links for Arduino Pins since the documents do not exist.

2017-06-15 13:25 UTC, ewpatton commented
This will need rebasing/updating after #137 is merged. Do not merge.

2017-06-15 16:27 UTC, ewpatton commented
This should be the final version of extensions and documentation barring any requests for changes during review. @marksherman @afmckinney

2017-06-15 20:58 UTC, marksherman requested changes

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/MicroBitMagnetometer.md
> +The <code>Microbit_Magnetometer</code> provides App Inventor users with the ability toconfigure the BBC micro:bit's on-board magnetometer and receive one or more magnetometer samples via the appropri
"toconfigure"

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/MicroBitUart.md
> ++ <a name="RequestTXCharacteristic"></a>`RequestTXCharacteristic` – Request notifications of messages received from the micro:bit's serial UART. New messages will
Request -> Requests

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/MicroBitUart.md
> ++ <a name="StopTXCharacteristicUpdates"></a>`StopTXCharacteristicUpdates` – Stop receiving updates from the micro:bit's serial UART. Note that there may be pending
Stop -> Stops

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/Arduino101Pins.md
> +<strong>More links</strong><ul><li>Download a <a href='http://iot.appinventor.mit.edu/assets/samples/Arduino101Pins.aia' target='_blank'>sample project</a> for the Arduino 101 Pins.</li><li>View the
`-->` is rendering, along with the whole paragraph that you tried to comment out.

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> ++ <a name="ConnectedDeviceName"></a>`ConnectedDeviceName` –
no descriptive sentence?

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> ++ <a name="ConnectionTimeout"></a>`ConnectionTimeout` – The amount of time, in seconds, that the BluetoothLE component will wait for a connection to be established with a device when <a href='#Connec
> The amount of time, in seconds, that the BluetoothLE component will wait for a connection to be established with a device when Connection or ConnectWithAddress.

when what?

Also, "Connection" and "ConnectWithAddress" are rendering differently. The first code tag is a close-tag.

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> ++ <a name="DeviceServices"></a>`DeviceServices` –
no descriptive sentence

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> ++ <a name="ReadStrings"></a>`ReadStrings` – Reads one or more null-terminated strings from a connected BluetoothLE device. Service Unique ID
"Unique ID" and "UniqueID" both present in same sentence. Based on other entries the space should be used.

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> ++ <a name="RegisterForFloats"></a>`RegisterForFloats` – Register to receive updates when one or more floating point values from a connected Bluetooth device change.
should indeed be "Registers"

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> + value or a list of values. If <code>shortFloats</code> is true, then each numeric value will be
Block image says "shortFloat" without the 's'. The description says "shortFloats" three times

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> + be a single numeric value or a list of values. If <code>shortFloats</code> is false,
same thing: "shortFloat" in the block image but "shortFloats" in the text

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> + 2147483647. If signed is false, the acceptable values are between 0 and 4294967295.
rendering as the beginning of a numbered list. Remove line break and it should be ok, I hope.

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> + value or a list of values. If signed is true, the acceptable values are between -32768 and 32767.
codeify "signed"

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> + be a single numeric value or a list of values. If signed is true, the acceptable values are
codeify "signed"

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> + be a single numeric value or a list of values. If signed is true, the acceptable values are
codeify "signed"

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> +       Send the string encoded as UTF-8 (false) or UTF-16 (true) code points.
say true-case first (this bug may exist elsewhere, too)

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> +       Send the string encoded as UTF-8 (false) or UTF-16 little endian (true) code points.
definitely exists elsewhere. say true case first

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> + connected Bluetooth device. Depending on the <code>shortFloats</code> parameter of the last call to
is it shortFloats or shortFloat (with or without suffix s)

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> + will contain numbers ranging from 0 to 4294967296 (<code>signed = false</code>) or
sign or signed?

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> + will contain numbers ranging from 0 to 65535 (<code>signed = false</code>) or -32768 to 32767
sign or signed?

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> + will contain either a UTF-8 decoded (<code>utf16 = false</code>) or UTF-16 little endian
say true first

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/MicroBitIoPin.md
> +The <code>Microbit_Io_Pin</code> component lets users configure the BBC micro:bit's analog pins for input and output, and to read, write, and request notifications for theI/O pin states.
space between theI/O

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/MicroBitUart.md
> +The <code>Microbit_Uart</code> sensor provides App Inventor users with the ability to read from and write strings to the BBC micro:bit's serial UART port.
why mention users? Just say "provides" 
(Also, Hal came in today with a new mission that will be against the word "users")

2017-06-15 20:58 UTC, marksherman commented on docs/src/app/pages/MicroBitUart.md
> ++ <a name="WriteRXCharacteristic"></a>`WriteRXCharacteristic` – Write the given value <code>UART_TX</code> to the micro:bit. The size of the message will
Writes

2017-06-16 00:04 UTC, ewpatton commented
I've pushed updated documentation that should address these issues (and a few that weren't documented but of the same variety).

2017-06-16 12:44 UTC, marksherman requested changes
I love all your new intro wordings. Just one typo.

2017-06-16 12:44 UTC, marksherman commented on docs/src/app/pages/BluetoothLEIntro.md
> +       Interpret the string content as UTF-16 (true) or UTF-9 (false) code points.
UTF-9?

2017-06-16 13:01 UTC, merged